# Generated by Django 5.1.5 on 2025-02-03 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trucks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cab_no', models.CharField(max_length=14, null=True)),
                ('truck_no', models.CharField(max_length=14, null=True)),
                ('Officer', models.CharField(max_length=25, null=True)),
            ],
        ),
    ]
