# Generated by Django 5.1.5 on 2025-02-03 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('truck', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trucks',
            new_name='Truck',
        ),
    ]
