# Generated by Django 5.1.5 on 2025-02-03 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truck', '0002_rename_trucks_truck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='cab_no',
            field=models.CharField(default='dct-1b-003', max_length=14),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='truck',
            name='truck_no',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
