# Generated by Django 5.1.5 on 2025-02-03 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truck', '0003_alter_truck_cab_no_alter_truck_truck_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='Officer',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
