# Generated by Django 5.1.5 on 2025-02-03 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('truck', '0004_alter_truck_officer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='truck',
            old_name='Officer',
            new_name='officer',
        ),
    ]
