# Generated by Django 5.1.5 on 2025-02-05 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truck', '0005_rename_officer_truck_officer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cab_no', models.CharField(max_length=14)),
            ],
        ),
    ]
