# Generated by Django 5.1.5 on 2025-02-05 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truck', '0006_exit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exited',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cab_no', models.CharField(max_length=14)),
            ],
        ),
        migrations.RenameModel(
            old_name='Exit',
            new_name='Admited',
        ),
    ]
