# Generated by Django 5.1.5 on 2025-02-05 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('truck', '0007_exited_rename_exit_admited'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admited',
            new_name='Selection',
        ),
    ]
