# Generated by Django 5.1.5 on 2025-02-05 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truck', '0009_exited_date_selection_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='exited',
            name='officer',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='selection',
            name='officer',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
