# Generated by Django 5.1.5 on 2025-02-05 13:47

import truck.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('truck', '0011_rename_exited_exit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exit',
            name='cab_no',
            field=truck.models.UpperCharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='selection',
            name='cab_no',
            field=truck.models.UpperCharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='truck',
            name='cab_no',
            field=truck.models.UpperCharField(max_length=14),
        ),
    ]
