# Generated by Django 5.1.5 on 2025-02-25 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truck', '0013_admmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='fleet',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
