# Generated by Django 5.1.5 on 2025-02-25 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truck', '0014_truck_fleet'),
    ]

    operations = [
        migrations.AddField(
            model_name='admmission',
            name='fleet',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='exit',
            name='fleet',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='selection',
            name='fleet',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
