# Generated by Django 5.1.5 on 2025-04-12 16:27

import truck.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truck', '0015_admmission_fleet_exit_fleet_selection_fleet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_date', models.DateField()),
                ('cab_no', truck.models.UpperCharField(max_length=14)),
                ('notification', models.CharField(max_length=10, unique=True)),
                ('type', models.CharField(max_length=2)),
                ('description', models.TextField()),
                ('officer', models.CharField(blank=True, max_length=25, null=True)),
                ('fleet', models.CharField(blank=True, max_length=14, null=True)),
                ('reported_by', models.CharField(blank=True, max_length=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrucksInsideWorkshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cab_no', truck.models.UpperCharField(max_length=14)),
                ('officer', models.CharField(blank=True, max_length=25, null=True)),
                ('fleet', models.CharField(blank=True, max_length=14, null=True)),
                ('admmited', models.DateField(auto_now_add=True)),
                ('exited', models.DateField(blank=True)),
            ],
        ),
    ]
